force_cast: warning
force_try: warning

line_length:
  warning: 150
  error: 200

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 40
  error: 120

opt_in_rules:
  - empty_count
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet

excluded: 
- Pods
